/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.DataAccess;
import Classes.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan Ng, Sareindra
 */
public class PeopleViewVaxPrg extends javax.swing.JFrame {

    /**
     * Creates new form ViewVaxPrgDetails
     */
    public PeopleViewVaxPrg() {
        initComponents();
        icPassportNoTxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleCardLabel = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        ageTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        telNoTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        telNoLabel = new javax.swing.JLabel();
        icPassportNoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        icPassportNoTxt = new javax.swing.JTextField();
        titleCardLabel2 = new javax.swing.JLabel();
        modifyDetailsBtn = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        titleCard = new javax.swing.JLabel();
        backToMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleCardLabel.setText("Please enter your IC/ Passport No.:");

        searchBtn.setText("Search/ View");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        nameLabel.setText("Name:");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ageLabel.setText("Age:");
        ageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        genderLabel.setText("Gender (M/F):");
        genderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        telNoLabel.setText("Telephone No.:");
        telNoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        icPassportNoLabel.setText("IC/Passport Number:");
        icPassportNoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        emailLabel.setText("Email:");
        emailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        addressLabel.setText("Address:");
        addressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        titleCardLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        titleCardLabel2.setText("Your Record:");

        modifyDetailsBtn.setText("Modify");
        modifyDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyDetailsBtnActionPerformed(evt);
            }
        });

        errorMessageLabel.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        errorMessageLabel.setForeground(new java.awt.Color(255, 51, 51));

        titleCard.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        titleCard.setText("VIEW SELF RECORDS");

        backToMenuBtn.setText("Back to Menu");
        backToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(titleCardLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(titleCardLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToMenuBtn)
                .addGap(60, 60, 60)
                .addComponent(modifyDetailsBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleCard)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailLabel)
                            .addComponent(addressLabel)
                            .addComponent(telNoLabel)
                            .addComponent(genderLabel)
                            .addComponent(ageLabel)
                            .addComponent(nameLabel)))
                    .addComponent(icPassportNoLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(telNoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(genderTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ageTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icPassportNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleCardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(30, 30, 30)
                .addComponent(titleCardLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNoLabel)
                    .addComponent(telNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icPassportNoLabel)
                    .addComponent(icPassportNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyDetailsBtn)
                    .addComponent(backToMenuBtn))
                .addGap(41, 41, 41)
                .addComponent(errorMessageLabel)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String id = searchTxt.getText();
        String[] ary = DataAccess.get_data_by_var("People.txt", id, 8, 7);

        if (!searchTxt.getText().equals("")) {
            if (ary[0] == null) {
                JOptionPane.showMessageDialog(null, "Record not found.");
                searchTxt.setText("");
            } else {
                nameTxt.setText(ary[0]);
                ageTxt.setText(ary[1]);
                genderTxt.setText(ary[2]);
                telNoTxt.setText(ary[3]);
                emailTxt.setText(ary[4]);
                addressTxt.setText(ary[5]);
                icPassportNoTxt.setText(ary[7]);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Some fields are empty");
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void modifyDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyDetailsBtnActionPerformed
        if (nameTxt.getText().equals("") || ageTxt.getText().equals("") || genderTxt.getText().equals("") || telNoTxt.getText().equals("")
                || emailTxt.getText().equals("") || addressTxt.getText().equals("") || icPassportNoTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some Fields are Empty!");
        } else {
            String search = searchTxt.getText();
            Person person = new Person();

            String errorMessages = "";

            String name = nameTxt.getText();
            errorMessages += person.validate_age(ageTxt.getText());
            errorMessages += person.validate_gender(genderTxt.getText());
            int age = 0;
            char gender = 0;
            if (errorMessages.isEmpty()) {
                age = Integer.parseInt(ageTxt.getText());
                gender = genderTxt.getText().charAt(0);
            }

            String tel_no = telNoTxt.getText();
            String email = emailTxt.getText();
            String address = addressTxt.getText();

            person.setName(name);
            person.setAge(age);
            person.setGender(gender);
            person.setTel_no(tel_no);
            person.setEmail(email);
            person.setAddress(address);

            errorMessages += person.validate_name();
            errorMessages += person.validate_tel_no();
            errorMessages += person.validate_email();
            errorMessages += person.validate_address();

            if (errorMessages.isEmpty()) {
                person.modify_person_details(search, "modify");
                JOptionPane.showMessageDialog(null, "Record updated.");
            } else {
                errorMessageLabel.setText(errorMessages);
            }
        }
    }//GEN-LAST:event_modifyDetailsBtnActionPerformed

    private void backToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuBtnActionPerformed
        this.setVisible(false);
        new PeopleMenu().setVisible(true);
    }//GEN-LAST:event_backToMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleViewVaxPrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleViewVaxPrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleViewVaxPrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleViewVaxPrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleViewVaxPrg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backToMenuBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JLabel icPassportNoLabel;
    private javax.swing.JTextField icPassportNoTxt;
    private javax.swing.JButton modifyDetailsBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JTextField telNoTxt;
    private javax.swing.JLabel titleCard;
    private javax.swing.JLabel titleCardLabel;
    private javax.swing.JLabel titleCardLabel2;
    // End of variables declaration//GEN-END:variables
}
