/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.Appointment;
import Classes.DataAccess;
import Enum.VaxStatus;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan Ng, Sareindra
 */
public class PeopleRegisterVaxApt extends javax.swing.JFrame {

    /**
     * Creates new form RegisterVaxApt
     */
    public PeopleRegisterVaxApt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleCard = new javax.swing.JLabel();
        icPassportNoLabel = new javax.swing.JLabel();
        vaccineNameLabel = new javax.swing.JLabel();
        vaxNameComboBox = new javax.swing.JComboBox<>();
        icPassportNoTxt = new javax.swing.JTextField();
        registerAptBtn = new javax.swing.JButton();
        backToMenuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleCard.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        titleCard.setText("REGISTER VACCINATION APPOINTMENT");

        icPassportNoLabel.setText("IC/Passport Number:");
        icPassportNoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        vaccineNameLabel.setText("Choose Vaccine:");

        vaxNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pfizer", "Aztrazeneca", "Sinovac" }));

        registerAptBtn.setText("Register Appointment");
        registerAptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerAptBtnActionPerformed(evt);
            }
        });

        backToMenuBtn.setText("Back to Menu");
        backToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleCard)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icPassportNoLabel)
                            .addComponent(vaccineNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icPassportNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vaxNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerAptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backToMenuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titleCard)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icPassportNoLabel)
                    .addComponent(icPassportNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaccineNameLabel)
                    .addComponent(vaxNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(registerAptBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backToMenuBtn)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuBtnActionPerformed
        this.setVisible(false);
        new PeopleMenu().setVisible(true);
    }//GEN-LAST:event_backToMenuBtnActionPerformed

    private void registerAptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerAptBtnActionPerformed
        Appointment apt = new Appointment();
        String ic_passport_no = icPassportNoTxt.getText();
        apt.setIc_passport_no(ic_passport_no);

        //check if input exists in People.txt
        if (apt.validate_ic_passport_no("People.txt", ic_passport_no, 7)) {

            //setting vax first, second, booster dose date fields
            if (vaxNameComboBox.getSelectedItem().equals("Pfizer")) {
                assign_aptdetails(apt, "Pfizer");
            } else if (vaxNameComboBox.getSelectedItem().equals("Aztrazeneca")) {
                assign_aptdetails(apt, "Aztrazeneca");
            } else if (vaxNameComboBox.getSelectedItem().equals("Sinovac")) {
                assign_aptdetails(apt, "Sinovac");
            } else {
                JOptionPane.showMessageDialog(null, "Something went wrong, please try again.");
            }

            File f = new File("Appointment.txt");
            if (f.exists() && !f.isDirectory()) {
                if (apt.validate_ic_passport_no("Appointment.txt", ic_passport_no, 0)) {
                    JOptionPane.showMessageDialog(null, "Duplicate record detected! Please try again.");
                } else {
                    apt.register_vax_apt();
                    icPassportNoTxt.setText("");
                    vaxNameComboBox.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(null, "Registration Successful.");
                }
            } else {
                apt.register_vax_apt();
                icPassportNoTxt.setText("");
                vaxNameComboBox.setSelectedIndex(0);
                JOptionPane.showMessageDialog(null, "Registration Successful.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "IC/Passport Number not found!\nPlease register first.");
        }
    }//GEN-LAST:event_registerAptBtnActionPerformed

    public void assign_aptdetails(Appointment apt, String vax_name) {
        String centre_id = apt.validate_vax_quantity(vax_name);
        if (DataAccess.isNumeric(centre_id)) {
            apt.setVaccine_name(vaxNameComboBox.getSelectedItem().toString());
            apt.setAppointment_id(apt.generateID());
            apt.setCentre_name(DataAccess.get_data_by_var("Centre.txt", centre_id, 3, 0)[1]);
            apt.setCentre_address(DataAccess.get_data_by_var("Centre.txt", centre_id, 3, 0 )[2]);
            apt.setFirst_dose_date(apt.setfdd());
            apt.setSecond_dose_date(apt.setsdd(apt.retrieve_time_delta(vax_name, "Second dose")));
            apt.setBooster_dose_date(apt.setbdd(apt.retrieve_time_delta(vax_name, "Booster dose")));
            apt.setVax_status(VaxStatus.NOT_VACCINATED.name());
        } else {
            JOptionPane.showMessageDialog(null, centre_id);//centre id will be error if all centres have insufficient vacs
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleRegisterVaxApt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleRegisterVaxApt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleRegisterVaxApt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleRegisterVaxApt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleRegisterVaxApt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMenuBtn;
    private javax.swing.JLabel icPassportNoLabel;
    private javax.swing.JTextField icPassportNoTxt;
    private javax.swing.JButton registerAptBtn;
    private javax.swing.JLabel titleCard;
    private javax.swing.JLabel vaccineNameLabel;
    private javax.swing.JComboBox<String> vaxNameComboBox;
    // End of variables declaration//GEN-END:variables
}
