/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.DataAccess;
import Classes.Person;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.ListIterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan Ng, Sareindra
 */
public class PersonnelViewVaxPrg extends javax.swing.JFrame {

    /**
     * Creates new form ViewVaxPrgDetails
     */
    private String user_type = "";
    private ArrayList<String[]> arrayList;
    private ListIterator<String[]> listIterator;
    int size;

    public PersonnelViewVaxPrg(String user_type) {
        initComponents();

        this.user_type = user_type;
        arrayList = DataAccess.get_data("People.txt");
        size = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ageTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        telNoTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        telNoLabel = new javax.swing.JLabel();
        icPassportNoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        icPassportNoTxt = new javax.swing.JTextField();
        titleCardLabel2 = new javax.swing.JLabel();
        modifyDetailsBtn = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        firstBtn = new javax.swing.JButton();
        lastBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        titleCardLabel = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        backToMenuBtn = new javax.swing.JButton();
        titleCardLabel3 = new javax.swing.JLabel();
        citizenshipLabel = new javax.swing.JLabel();
        citizenRBtn = new javax.swing.JRadioButton();
        noncitizenRBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Name:");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        ageLabel.setText("Age:");
        ageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        genderLabel.setText("Gender (M/F):");
        genderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        telNoLabel.setText("Telephone No.:");
        telNoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        icPassportNoLabel.setText("IC/Passport Number:");
        icPassportNoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        emailLabel.setText("Email:");
        emailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        addressLabel.setText("Address:");
        addressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        titleCardLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        titleCardLabel2.setText("VIEW ALL PEOPLE RECORDS");

        modifyDetailsBtn.setText("Modify Records");
        modifyDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyDetailsBtnActionPerformed(evt);
            }
        });

        errorMessageLabel.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        errorMessageLabel.setForeground(new java.awt.Color(255, 51, 51));

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        previousBtn.setText("Previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });

        firstBtn.setText("First");
        firstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstBtnActionPerformed(evt);
            }
        });

        lastBtn.setText("Last");
        lastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove Records");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        titleCardLabel.setText("Search by IC/ Passport No.:");

        searchBtn.setText("Search/ View");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        backToMenuBtn.setText("Back to Menu");
        backToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuBtnActionPerformed(evt);
            }
        });

        titleCardLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        titleCardLabel3.setText("Vaccination Programme Records");

        citizenshipLabel.setText("Citizenship:");

        citizenRBtn.setText("Citizen");
        citizenRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenRBtnActionPerformed(evt);
            }
        });

        noncitizenRBtn.setText("Non-Citizen");
        noncitizenRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noncitizenRBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleCardLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchBtn)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(modifyDetailsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(removeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(citizenRBtn)
                                    .addComponent(icPassportNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(backToMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(82, 82, 82)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(noncitizenRBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailLabel)
                                    .addComponent(addressLabel)
                                    .addComponent(telNoLabel)
                                    .addComponent(genderLabel)
                                    .addComponent(ageLabel)
                                    .addComponent(nameLabel)
                                    .addComponent(citizenshipLabel)
                                    .addComponent(icPassportNoLabel))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telNoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(titleCardLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(previousBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firstBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleCardLabel2)
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleCardLabel2)
                .addGap(18, 18, 18)
                .addComponent(titleCardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(22, 22, 22)
                .addComponent(titleCardLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telNoLabel)
                    .addComponent(telNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(citizenRBtn)
                            .addComponent(noncitizenRBtn))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(citizenshipLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icPassportNoLabel)
                    .addComponent(icPassportNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstBtn)
                    .addComponent(modifyDetailsBtn)
                    .addComponent(lastBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn)
                    .addComponent(nextBtn)
                    .addComponent(previousBtn))
                .addGap(19, 19, 19)
                .addComponent(backToMenuBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorMessageLabel)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modifyDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyDetailsBtnActionPerformed
        if (nameTxt.getText().equals("") || ageTxt.getText().equals("") || genderTxt.getText().equals("") || telNoTxt.getText().equals("")
                || emailTxt.getText().equals("") || addressTxt.getText().equals("") || icPassportNoTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some fields are Empty!");
        } else {
            Person person = new Person();

            String errorMessages = "";

            String name = nameTxt.getText();
            errorMessages += person.validate_age(ageTxt.getText());
            errorMessages += person.validate_gender(genderTxt.getText());
            int age = 0;
            char gender = 0;
            if (errorMessages.isEmpty()) {
                age = Integer.parseInt(ageTxt.getText());
                gender = genderTxt.getText().charAt(0);
            }

            String tel_no = telNoTxt.getText();
            String email = emailTxt.getText();
            String address = addressTxt.getText();

            person.setName(name);
            person.setAge(age);
            person.setGender(gender);
            person.setTel_no(tel_no);
            person.setEmail(email);
            person.setAddress(address);
            if (citizenRBtn.isSelected()) {
                person.setIs_citizen(true);
            } else {
                person.setIs_citizen(false);
            }

            errorMessages += person.validate_name();
            errorMessages += person.validate_tel_no();
            errorMessages += person.validate_email();
            errorMessages += person.validate_address();

            if (errorMessages.isEmpty()) {
                arrayList = person.modify_person_details(icPassportNoTxt.getText(), "modify");
                JOptionPane.showMessageDialog(null, "Record updated.");
            } else {
                JOptionPane.showMessageDialog(null, errorMessages);
            }
        }
    }//GEN-LAST:event_modifyDetailsBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        Person person = new Person();
        arrayList = person.modify_person_details(icPassportNoTxt.getText(), "remove");
        listIterator = arrayList.listIterator();
        clearFields();
        JOptionPane.showMessageDialog(null, "Record removed.");
    }//GEN-LAST:event_removeBtnActionPerformed

    private void firstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBtnActionPerformed
        size = arrayList.size();
        listIterator = arrayList.listIterator();
        String[] ary = listIterator.next();
        nameTxt.setText(ary[0]);
        ageTxt.setText(ary[1]);
        genderTxt.setText(ary[2]);
        telNoTxt.setText(ary[3]);
        emailTxt.setText(ary[4]);
        addressTxt.setText(ary[5]);
        if (ary[6].equals("true")) {
            citizenRBtn.setSelected(true);
            noncitizenRBtn.setSelected(false);
        } else {
            citizenRBtn.setSelected(false);
            noncitizenRBtn.setSelected(true);
        }
        icPassportNoTxt.setText(ary[7]);
    }//GEN-LAST:event_firstBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        if (nameTxt.getText().equals("") || ageTxt.getText().equals("") || genderTxt.getText().equals("") || telNoTxt.getText().equals("")
                || emailTxt.getText().equals("") || addressTxt.getText().equals("") || icPassportNoTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some fields are Empty!");
        } else {
            if (listIterator.hasNext()) {
                String[] ary = listIterator.next();
                nameTxt.setText(ary[0]);
                ageTxt.setText(ary[1]);
                genderTxt.setText(ary[2]);
                telNoTxt.setText(ary[3]);
                emailTxt.setText(ary[4]);
                addressTxt.setText(ary[5]);
                if (ary[6].equals("true")) {
                    citizenRBtn.setSelected(true);
                    noncitizenRBtn.setSelected(false);
                } else {
                    citizenRBtn.setSelected(false);
                    noncitizenRBtn.setSelected(true);
                }
                icPassportNoTxt.setText(ary[7]);
            } else {
                JOptionPane.showMessageDialog(null, "You reached the end of the records.");
            }
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        if (nameTxt.getText().equals("") || ageTxt.getText().equals("") || genderTxt.getText().equals("") || telNoTxt.getText().equals("")
                || emailTxt.getText().equals("") || addressTxt.getText().equals("") || icPassportNoTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some fields are Empty!");
        } else {
            if (listIterator.hasPrevious()) {
                String[] ary = listIterator.previous();
                nameTxt.setText(ary[0]);
                ageTxt.setText(ary[1]);
                genderTxt.setText(ary[2]);
                telNoTxt.setText(ary[3]);
                emailTxt.setText(ary[4]);
                addressTxt.setText(ary[5]);
                if (ary[6].equals("true")) {
                    citizenRBtn.setSelected(true);
                    noncitizenRBtn.setSelected(false);
                } else {
                    citizenRBtn.setSelected(false);
                    noncitizenRBtn.setSelected(true);
                }
                icPassportNoTxt.setText(ary[7]);
            } else {
                JOptionPane.showMessageDialog(null, "You reached the start of the records.");
            }
        }
    }//GEN-LAST:event_previousBtnActionPerformed

    private void lastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastBtnActionPerformed
        size = arrayList.size();
        listIterator = arrayList.listIterator(arrayList.size());
        if (listIterator.hasPrevious()) {
            String[] ary = listIterator.previous();
            nameTxt.setText(ary[0]);
            ageTxt.setText(ary[1]);
            genderTxt.setText(ary[2]);
            telNoTxt.setText(ary[3]);
            emailTxt.setText(ary[4]);
            addressTxt.setText(ary[5]);
            if (ary[6].equals("true")) {
                citizenRBtn.setSelected(true);
                noncitizenRBtn.setSelected(false);
            } else {
                citizenRBtn.setSelected(false);
                noncitizenRBtn.setSelected(true);
            }
            icPassportNoTxt.setText(ary[7]);
        } else {
            JOptionPane.showMessageDialog(null, "You reached the start of the records.");
        }
    }//GEN-LAST:event_lastBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String search = searchTxt.getText();
        try {
            BufferedReader br = new BufferedReader(new FileReader("People.txt"));
            String line;
            while ((line = br.readLine()) != null) {
                String[] ary = line.split(":");
                if (ary.length < 1) {
                    break;
                }
                if (search.equals(ary[7])) {
                    Arrays.toString(ary);
                    nameTxt.setText(ary[0]);
                    ageTxt.setText(ary[1]);
                    genderTxt.setText(ary[2]);
                    telNoTxt.setText(ary[3]);
                    emailTxt.setText(ary[4]);
                    addressTxt.setText(ary[5]);
                    if (ary[6].equals("true")) {
                        citizenRBtn.setSelected(true);
                        noncitizenRBtn.setSelected(false);
                    } else {
                        citizenRBtn.setSelected(false);
                        noncitizenRBtn.setSelected(true);
                    }
                    icPassportNoTxt.setText(ary[7]);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void backToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuBtnActionPerformed
        this.setVisible(false);
        new PersonnelMenu(this.user_type).setVisible(true);
    }//GEN-LAST:event_backToMenuBtnActionPerformed

    private void citizenRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenRBtnActionPerformed
        if (citizenRBtn.isSelected()) {
            noncitizenRBtn.setSelected(false);
        }
    }//GEN-LAST:event_citizenRBtnActionPerformed

    private void noncitizenRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noncitizenRBtnActionPerformed
        if (noncitizenRBtn.isSelected()) {
            citizenRBtn.setSelected(false);
        }
    }//GEN-LAST:event_noncitizenRBtnActionPerformed

    void clearFields() {
        size = arrayList.size();
        listIterator = arrayList.listIterator();
        String[] ary = listIterator.next();
        nameTxt.setText(ary[0]);
        ageTxt.setText(ary[1]);
        genderTxt.setText(ary[2]);
        telNoTxt.setText(ary[3]);
        emailTxt.setText(ary[4]);
        addressTxt.setText(ary[5]);
        if (ary[6].equals("true")) {
            citizenRBtn.setSelected(true);
            noncitizenRBtn.setSelected(false);
        } else {
            citizenRBtn.setSelected(false);
            noncitizenRBtn.setSelected(true);
        }
        icPassportNoTxt.setText(ary[7]);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelViewVaxPrg.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelViewVaxPrg.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelViewVaxPrg.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelViewVaxPrg.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelViewVaxPrg("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backToMenuBtn;
    private javax.swing.JRadioButton citizenRBtn;
    private javax.swing.JLabel citizenshipLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JButton firstBtn;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JLabel icPassportNoLabel;
    private javax.swing.JTextField icPassportNoTxt;
    private javax.swing.JButton lastBtn;
    private javax.swing.JButton modifyDetailsBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton noncitizenRBtn;
    private javax.swing.JButton previousBtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel telNoLabel;
    private javax.swing.JTextField telNoTxt;
    private javax.swing.JLabel titleCardLabel;
    private javax.swing.JLabel titleCardLabel2;
    private javax.swing.JLabel titleCardLabel3;
    // End of variables declaration//GEN-END:variables
}
