/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.Citizen;
import Classes.Person;

/**
 *
 * @author Ryan Ng
 */
public class PersonnelMenu extends javax.swing.JFrame {

    /**
     * Creates new form PeopleMenu
     */
    public PersonnelMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerVaxAptBtn = new javax.swing.JButton();
        viewVaxAptBtn = new javax.swing.JButton();
        viewDetailsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backToLoginBtn = new javax.swing.JButton();
        viewVaxSupplyBtn = new javax.swing.JButton();
        registerPersonnelBtn = new javax.swing.JButton();
        viewDetailsBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        registerVaxAptBtn.setText("Register Vaccination Appointment");
        registerVaxAptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerVaxAptBtnActionPerformed(evt);
            }
        });

        viewVaxAptBtn.setText("View Vaccination Appointment / Vaccination Status");
        viewVaxAptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVaxAptBtnActionPerformed(evt);
            }
        });

        viewDetailsBtn.setText("View / Edit Vaccination Programme Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("PERSONNEL MAIN MENU");

        backToLoginBtn.setText("Back to Login");
        backToLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginBtnActionPerformed(evt);
            }
        });

        viewVaxSupplyBtn.setText("View / Edit Vaccine Supply");
        viewVaxSupplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVaxSupplyBtn(evt);
            }
        });

        registerPersonnelBtn.setText("Register New Personnel");
        registerPersonnelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPersonnelBtnActionPerformed(evt);
            }
        });

        viewDetailsBtn1.setText("View / Edit Personnel Records");
        viewDetailsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewVaxSupplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewVaxAptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerVaxAptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewDetailsBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                                .addComponent(registerPersonnelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(viewDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(backToLoginBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerPersonnelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(viewDetailsBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerVaxAptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewVaxAptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewVaxSupplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(backToLoginBtn)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        this.setVisible(false);
        new PersonnelViewVaxPrg().setVisible(true);
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void registerVaxAptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerVaxAptBtnActionPerformed
        this.setVisible(false);
        new PersonnelRegisterVaxApt().setVisible(true);
    }//GEN-LAST:event_registerVaxAptBtnActionPerformed

    private void viewVaxAptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVaxAptBtnActionPerformed
        this.setVisible(false);
        new PersonnelViewVaxApt().setVisible(true);
    }//GEN-LAST:event_viewVaxAptBtnActionPerformed

    private void backToLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginBtnActionPerformed
        this.setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_backToLoginBtnActionPerformed

    private void viewVaxSupplyBtn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVaxSupplyBtn
        this.setVisible(false);
        new VaccineSupply().setVisible(true);
    }//GEN-LAST:event_viewVaxSupplyBtn

    private void registerPersonnelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPersonnelBtnActionPerformed
        this.setVisible(false);
        new RegisterPersonnelPage().setVisible(true);
    }//GEN-LAST:event_registerPersonnelBtnActionPerformed

    private void viewDetailsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtn1ActionPerformed
        this.setVisible(false);
        new ViewPersonnelRecords().setVisible(true);
    }//GEN-LAST:event_viewDetailsBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonnelMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToLoginBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registerPersonnelBtn;
    private javax.swing.JButton registerVaxAptBtn;
    private javax.swing.JButton viewDetailsBtn;
    private javax.swing.JButton viewDetailsBtn1;
    private javax.swing.JButton viewVaxAptBtn;
    private javax.swing.JButton viewVaxSupplyBtn;
    // End of variables declaration//GEN-END:variables
}
