/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.DataAccess;
import Classes.Person;
import Classes.Personnel;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan Ng, Sareindra
 */
public class RegisterPersonnelPage extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPage
     */
    private String user_type = "";

    public RegisterPersonnelPage(String user_type) {
        initComponents();
        this.user_type = user_type;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        empIDLabel = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        empIDTxt = new javax.swing.JTextField();
        TITLE = new javax.swing.JLabel();
        citizenshipLabel = new javax.swing.JLabel();
        icPassportNoLabel = new javax.swing.JLabel();
        asRBtn = new javax.swing.JRadioButton();
        hpRBtn = new javax.swing.JRadioButton();
        icPassportNoTxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        errorMessageLabel = new javax.swing.JLabel();
        backToMenuBtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ageLabel.setText("Age:");

        genderLabel.setText("Gender (M/F):");

        empIDLabel.setText("Employee ID:");

        TITLE.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        TITLE.setText("REGISTER PERSONNEL PAGE");

        citizenshipLabel.setText("Job Position:");

        icPassportNoLabel.setText("IC Number:");

        asRBtn.setText("Admin Staff");
        asRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asRBtnActionPerformed(evt);
            }
        });

        hpRBtn.setText("Healthcare Personnel");
        hpRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpRBtnActionPerformed(evt);
            }
        });

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        errorMessageLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        errorMessageLabel.setForeground(new java.awt.Color(153, 0, 0));
        errorMessageLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        backToMenuBtn.setText("Back to Menu");
        backToMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuBtnActionPerformed(evt);
            }
        });

        nameLabel.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TITLE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(icPassportNoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(citizenshipLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empIDLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backToMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(genderTxt)
                            .addComponent(icPassportNoTxt)
                            .addComponent(nameTxt)
                            .addComponent(ageTxt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(asRBtn)
                                .addGap(18, 18, 18)
                                .addComponent(hpRBtn))
                            .addComponent(empIDTxt))))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TITLE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icPassportNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icPassportNoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(citizenshipLabel)
                    .addComponent(asRBtn)
                    .addComponent(hpRBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDLabel)
                    .addComponent(empIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(backToMenuBtn))
                .addGap(18, 18, 18)
                .addComponent(errorMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hpRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpRBtnActionPerformed
        if (hpRBtn.isSelected()) {
            asRBtn.setSelected(false);
            empIDTxt.setText("HP");
        }
    }//GEN-LAST:event_hpRBtnActionPerformed

    private void asRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asRBtnActionPerformed
        if (asRBtn.isSelected()) {
            hpRBtn.setSelected(false);
            empIDTxt.setText("AS");
        }
    }//GEN-LAST:event_asRBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        if (icPassportNoTxt.getText().equals("") || nameTxt.getText().equals("")
                || ageTxt.getText().equals("") || genderTxt.getText().equals("") || empIDTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Some fields are Empty!");
        } else {
            Person person = new Person();

            if (asRBtn.isSelected()) {
                hpRBtn.setSelected(false);
                String job_position = asRBtn.getText();
                assign_details(person, job_position);
            } else {
                asRBtn.setSelected(false);
                String job_position = hpRBtn.getText();
                assign_details(person, job_position);
            }
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void backToMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuBtnActionPerformed
        this.setVisible(false);
        new PersonnelMenu(this.user_type).setVisible(true);
    }//GEN-LAST:event_backToMenuBtnActionPerformed

    void assign_details(Person person, String job_position) {
        String errorMessages = "";

        String name = nameTxt.getText();
        String ic_no = icPassportNoTxt.getText();
        String emp_id = empIDTxt.getText();

        errorMessages += person.validate_age(ageTxt.getText());
        errorMessages += person.validate_gender(genderTxt.getText());

        int age = 0;
        char gender = 0;
        if (errorMessages.isEmpty()) {
            age = Integer.parseInt(ageTxt.getText());
            gender = genderTxt.getText().charAt(0);
        }

        Personnel personnel = new Personnel(person, ic_no, emp_id, job_position);
        personnel.setName(name);
        errorMessages += personnel.validate_name();
        personnel.setAge(age);
        personnel.setGender(gender);

        if (errorMessages.isEmpty()) {
            File f = new File("Personnel.txt");
            if (f.exists() && !f.isDirectory()) {
                if (DataAccess.validate_data("Personnel.txt", ic_no, 0) || DataAccess.validate_data("Personnel.txt", emp_id, 4)) {
                    JOptionPane.showMessageDialog(null, "Duplicate record detected! Please try again.");
                } else {
                    if (DataAccess.isNumeric(ic_no)) {
                        personnel.setIc_no(ic_no);
                        personnel.setEmp_id(emp_id);
                        personnel.setJob_position(job_position);

                        personnel.register_personnel();
                        clearFields();
                        JOptionPane.showMessageDialog(null, "Registration successful!\n" + "\n" + "Login Credentials\n"
                                + "Username: " + personnel.getIc_no() + "\n" + "Password: " + personnel.getEmp_id());
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid IC Number!");
                    }
                }
            } else {
                if (DataAccess.isNumeric(ic_no)) {
                    personnel.setIc_no(ic_no);
                    personnel.setEmp_id(emp_id);
                    personnel.setJob_position(job_position);

                    personnel.register_personnel();
                    clearFields();
                    JOptionPane.showMessageDialog(null, "Registration successful!\n" + "\n" + "Login Credentials\n"
                            + "Username: " + personnel.getIc_no() + "\n" + "Password: " + personnel.getEmp_id());
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid IC Number!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, errorMessages);
        }
    }

    void clearFields() {
        icPassportNoTxt.setText("");
        nameTxt.setText("");
        ageTxt.setText("");
        genderTxt.setText("");
        empIDTxt.setText("");
        asRBtn.setSelected(false);
        hpRBtn.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPersonnelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPersonnelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPersonnelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPersonnelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPersonnelPage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITLE;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JRadioButton asRBtn;
    private javax.swing.JButton backToMenuBtn;
    private javax.swing.JLabel citizenshipLabel;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JTextField empIDTxt;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JRadioButton hpRBtn;
    private javax.swing.JLabel icPassportNoLabel;
    private javax.swing.JTextField icPassportNoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
